#! /bin/bash
planroot=/opt/PAH	#if used on different machine, change the planroot folder o the folder with planners
#planroot=~/planners

if [ "$#" -ne 4 ]; then
    echo "usage: plan <ff|fd-fdss|fd-ms|fd-lmcut|lama|mercury|probe|symba|yahsp3> <simple|cost|extended> <p01|p02> <timeout(e.g. '10m')>"
    exit
fi

echo "planners root: $planroot"

ppwd=$PWD
#echo $ppwd

mkdir ./$2/$1

cd $planroot

rp=`python -c "import os.path; print os.path.relpath('$ppwd','$PWD')"`
echo "relative path: $rp"

echo "run: timeout --signal=KILL $4 ./plan-$1 $rp/$2/domain.pddl $rp/$2/$3.pddl $rp/$2/$1/$3.solution > $rp/$2/$1/$3.log"
timeout --signal=KILL $4 ./plan-$1 $rp/$2/domain.pddl $rp/$2/$3.pddl $rp/$2/$1/$3.solution > $rp/$2/$1/$3.log

echo "done"
